module.exports = {
  theme: {
    extend: {
      colors: {
        // ── Brand primitives ─────────────────────────────────────
        brand: {
          blue:           '#0043FF',
          pink:           '#FC4575',
          navy:           '#1B306C',
          // DS v2.5 descriptive names
          'pale-blue':    '#E6F1FD',
          'sky-blue':     '#B4D5FF',
          'electric-blue':'#00A0FF',
          'ocean-blue':   '#1773FF',
          'deep-blue':    '#115FD8',
          'baby-blue':    '#CDE5FF',
          'powder-blue':  '#AFD0F2',
          'ice-white':    '#F5F9FF',
          'pearl-gray':   '#DAE3EC',
          raspberry:      '#F23063',
          cherry:         '#D80E43',
        },
        // ── Semantic — v2.5 — background (surfaces) ──────────────
        background: {
          primary:              'var(--color-bg-primary)',
          secondary:            'var(--color-bg-secondary)',
          'secondary-hover':    'var(--color-bg-secondary-hover)',
          'secondary-pressed':  'var(--color-bg-secondary-pressed)',
          tertiary:             'var(--color-bg-tertiary)',
          canvas:               'var(--color-bg-canvas)',
          card:                 'var(--color-bg-card)',
          raised:               'var(--color-bg-raised)',
          accent:               'var(--color-bg-accent)',
          'accent-subtle':      'var(--color-bg-accent-subtle)',
          'accent-dark':        'var(--color-bg-accent-dark)',
          'accent-pink':        'var(--color-bg-accent-pink)',
          'accent-pink-hover':  'var(--color-bg-accent-pink-hover)',
          'accent-pink-pressed':'var(--color-bg-accent-pink-pressed)',
          transparent:          'var(--color-bg-transparent)',
          disable:              'var(--color-bg-disable)',
          overlay:              'var(--color-bg-overlay)',
          backdrop:             'var(--color-bg-backdrop)',
          'interactive-hover':  'var(--color-bg-interactive-hover)',
          'interactive-pressed':'var(--color-bg-interactive-pressed)',
          danger:               'var(--color-bg-danger)',
          'danger-hover':       'var(--color-bg-danger-hover)',
          'danger-pressed':     'var(--color-bg-danger-pressed)',
          'error-hover':        'var(--color-bg-error-hover)',
          'error-pressed':      'var(--color-bg-error-pressed)',
          // Status
          success:              'var(--color-bg-success)',
          error:                'var(--color-bg-error)',
          warning:              'var(--color-bg-warning)',
          info:                 'var(--color-bg-info)',
          critical:             'var(--color-bg-critical)',
          shipping:             'var(--color-bg-shipping)',
        },
        // ── Semantic — v2.5 — text (ink) ─────────────────────────
        text: {
          primary:              'var(--color-text-primary)',
          secondary:            'var(--color-text-secondary)',
          tertiary:             'var(--color-text-tertiary)',
          disable:              'var(--color-text-disable)',
          accent:               'var(--color-text-accent)',
          'on-accent':          'var(--color-text-on-accent)',
          invert:               'var(--color-text-invert)',
          placeholder:          'var(--color-text-placeholder)',
          link:                 'var(--color-text-link)',
          'link-visited':       'var(--color-text-link-visited)',
          'interactive-hover':  'var(--color-text-interactive-hover)',
          'interactive-pressed':'var(--color-text-interactive-pressed)',
          // Status
          success:              'var(--color-text-success)',
          'on-success':         'var(--color-text-on-success)',
          error:                'var(--color-text-error)',
          'on-error':           'var(--color-text-on-error)',
          'error-strong':       'var(--color-text-error-strong)',
          warning:              'var(--color-text-warning)',
          'on-warning':         'var(--color-text-on-warning)',
          'warning-strong':     'var(--color-text-warning-strong)',
          info:                 'var(--color-text-info)',
          'on-info':            'var(--color-text-on-info)',
          critical:             'var(--color-text-critical)',
          'on-critical':        'var(--color-text-on-critical)',
          shipping:             'var(--color-text-shipping)',
          'on-shipping':        'var(--color-text-on-shipping)',
        },
        // ── Semantic — v2.5 — border (line) ──────────────────────
        border: {
          primary:              'var(--color-border-primary)',
          secondary:            'var(--color-border-secondary)',
          accent:               'var(--color-border-accent)',
          subtle:               'var(--color-border-subtle)',
          disable:              'var(--color-border-disable)',
          'on-dark':            'var(--color-border-on-dark)',
          focus:                'var(--color-border-focus)',
          ring:                 'var(--color-border-ring)',
          ghost:                'var(--color-border-ghost)',
          'interactive-hover':  'var(--color-border-interactive-hover)',
          'interactive-pressed':'var(--color-border-interactive-pressed)',
          // Status
          error:                'var(--color-border-error)',
          success:              'var(--color-border-success)',
          warning:              'var(--color-border-warning)',
          info:                 'var(--color-border-info)',
          critical:             'var(--color-border-critical)',
        },
        // ── Semantic — icon ───────────────────────────────────────
        icon: {
          primary:    'var(--color-icon-primary)',
          secondary:  'var(--color-icon-secondary)',
          tertiary:   'var(--color-icon-tertiary)',
          disable:    'var(--color-icon-disable)',
          accent:     'var(--color-icon-accent)',
          'on-accent':'var(--color-icon-on-accent)',
          invert:     'var(--color-icon-invert)',
          success:    'var(--color-icon-success)',
          error:      'var(--color-icon-error)',
          warning:    'var(--color-icon-warning)',
          info:       'var(--color-icon-info)',
          critical:   'var(--color-icon-critical)',
          shipping:   'var(--color-icon-shipping)',
        },

        // ── DEPRECATED v2.0 — kept for unmigrated components ─────
        // ponytail: remove per-component as each migrates to v2.5
        surface: {
          primary:          'var(--color-bg-primary)',
          secondary:        'var(--color-bg-secondary)',
          tertiary:         'var(--color-bg-tertiary)',
          accent:           'var(--color-bg-accent)',
          'accent-subtle':  'var(--color-bg-accent-subtle)',
          'accent-contrast':'var(--color-bg-accent-dark)',
          transparent:      'var(--color-bg-transparent)',
          disable:          'var(--color-bg-disable)',
          success:          'var(--color-bg-success)',
          error:            'var(--color-bg-error)',
          warning:          'var(--color-bg-warning)',
          info:             'var(--color-bg-info)',
          'secondary-hover':    'var(--color-bg-secondary-hover)',
          'secondary-pressed':  'var(--color-bg-secondary-pressed)',
          danger:               'var(--color-bg-danger)',
          'danger-hover':       'var(--color-bg-danger-hover)',
          'danger-pressed':     'var(--color-bg-danger-pressed)',
          'accent-pink':        'var(--color-bg-accent-pink)',
          'accent-pink-hover':  'var(--color-bg-accent-pink-hover)',
          'accent-pink-pressed':'var(--color-bg-accent-pink-pressed)',
        },
        ink: {
          primary:    'var(--color-text-primary)',
          secondary:  'var(--color-text-secondary)',
          tertiary:   'var(--color-text-tertiary)',
          disable:    'var(--color-text-disable)',
          accent:     'var(--color-text-accent)',
          'on-accent':'var(--color-text-on-accent)',
          invert:     'var(--color-text-invert)',
          success:    'var(--color-text-success)',
          error:      'var(--color-text-error)',
          warning:    'var(--color-text-warning)',
          info:       'var(--color-text-info)',
        },
        line: {
          primary:   'var(--color-border-primary)',
          secondary: 'var(--color-border-secondary)',
          accent:    'var(--color-border-accent)',
          subtle:    'var(--color-border-subtle)',
          disable:   'var(--color-border-disable)',
          focus:     'var(--color-border-focus)',
          error:     'var(--color-border-error)',
          success:   'var(--color-border-success)',
          invert:    'var(--color-border-on-dark)',
          ghost:     'var(--color-border-ghost)',
          'interactive-pressed': 'var(--color-border-interactive-pressed)',
        },

        // ── Base ─────────────────────────────────────────────────
        white: '#ffffff',
        black: '#000000',
        slate: {
          50:  '#f8fafc', 100: '#f1f5f9', 200: '#e2e8f0', 300: '#cbd5e1',
          400: '#94a3b8', 500: '#64748b', 600: '#475569', 700: '#334155',
          800: '#1e293b', 900: '#0f172a', 950: '#020617',
        },
      },

      fontFamily: {
        heading: ['Lexend', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
      },

      fontSize: {
        'ds-h1': ['var(--type-h1-size)', { lineHeight: 'var(--type-h1-lh)', fontWeight: 'var(--type-h1-weight)' }],
        'ds-h2': ['var(--type-h2-size)', { lineHeight: 'var(--type-h2-lh)', fontWeight: 'var(--type-h2-weight)' }],
        'ds-h3': ['var(--type-h3-size)', { lineHeight: 'var(--type-h3-lh)', fontWeight: 'var(--type-h3-weight)' }],
        'ds-h4': ['var(--type-h4-size)', { lineHeight: 'var(--type-h4-lh)', fontWeight: 'var(--type-h4-weight)' }],
        'ds-sub':['var(--type-sub-size)',{ lineHeight: 'var(--type-sub-lh)', fontWeight: 'var(--type-sub-weight)' }],
        'ds-lg': ['var(--type-lg-size)', { lineHeight: 'var(--type-lg-lh)', fontWeight: 'var(--type-lg-weight)' }],
        'ds-md': ['var(--type-md-size)', { lineHeight: 'var(--type-md-lh)', fontWeight: 'var(--type-md-weight)' }],
        'ds-sm': ['var(--type-sm-size)', { lineHeight: 'var(--type-sm-lh)', fontWeight: 'var(--type-sm-weight)' }],
        'ds-xs': ['var(--type-xs-size)', { lineHeight: 'var(--type-xs-lh)', fontWeight: 'var(--type-xs-weight)' }],
      },
    },
  },
  safelist: [
    { pattern: /^(p|m|gap|px|py|pt|pb|pl|pr)-(0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)$/ },
    { pattern: /^(p|m|gap|px|py|pt|pb|pl|pr)-(0\.5|1\.5|2\.5|3\.5)$/ },
    { pattern: /^rounded(-none|-sm|-md|-lg|-xl|-2xl|-3xl|-full)?$/ },
    { pattern: /^border-(0|2|4|8)$/ },
    // v2.5 tokens
    { pattern: /^bg-background-(primary|secondary|secondary-hover|secondary-pressed|tertiary|canvas|card|raised|accent|accent-subtle|accent-dark|accent-pink|accent-pink-hover|accent-pink-pressed|transparent|disable|overlay|backdrop|interactive-hover|interactive-pressed|danger|danger-hover|danger-pressed|error-hover|error-pressed|success|error|warning|info|critical|shipping)(\/(10|20|50|100))?$/ },
    { pattern: /^text-text-(primary|secondary|tertiary|disable|accent|on-accent|invert|placeholder|link|link-visited|interactive-hover|interactive-pressed|success|on-success|error|on-error|error-strong|warning|on-warning|warning-strong|info|on-info|critical|on-critical|shipping|on-shipping)(\/(10|20|50|100))?$/ },
    { pattern: /^border-border-(primary|secondary|accent|subtle|disable|on-dark|focus|ring|ghost|interactive-hover|interactive-pressed|error|success|warning|info|critical)(\/(10|20|50|100))?$/ },
    { pattern: /^(bg|text|border)-icon-(primary|secondary|tertiary|disable|accent|on-accent|invert|success|error|warning|info|critical|shipping)(\/(10|20|50|100))?$/ },
    // Deprecated v2.0 (keep until all components migrate)
    { pattern: /^bg-surface-(primary|secondary|secondary-hover|secondary-pressed|tertiary|accent|accent-subtle|accent-contrast|transparent|disable|success|error|warning|info|danger|danger-hover|danger-pressed|accent-pink|accent-pink-hover|accent-pink-pressed)(\/(10|20|50|100))?$/ },
    { pattern: /^text-ink-(primary|secondary|tertiary|disable|accent|on-accent|invert|success|error|warning|info)(\/(10|20|50|100))?$/ },
    { pattern: /^border-line-(primary|secondary|accent|subtle|disable|focus|error|success|invert|ghost|interactive-pressed)(\/(10|20|50|100))?$/ },
    // Brand
    { pattern: /^(bg|text|border)-(brand-(blue|pink|navy|pale-blue|sky-blue|electric-blue|ocean-blue|deep-blue|baby-blue|powder-blue|ice-white|pearl-gray|raspberry|cherry))(\/(10|20|50|100))?$/ },
    { pattern: /^(bg|text|border)-slate-(50|100|200|300|400|500|600|700|800|900|950)(\/(10|20|50|100))?$/ },
    { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl)$/ },
    { pattern: /^text-ds-(h1|h2|h3|h4|sub|lg|md|sm|xs)$/ },
    { pattern: /^font-(normal|medium|semibold|bold)$/ },
    { pattern: /^font-(heading|body)$/ },
  ],
};
